---
- name: Deploy to Tomcat
  hosts: web
  become: yes
  tasks:
    - name: Copy WAR file to Tomcat
      copy:
        src: "/var/snap/jenkins/4865/workspace/MavenAnsible-CICD/target/MyMavenWebApp02.war"
        dest: "/opt/tomcat/webapps/MyMavenWebApp02.war"
        remote_src: no

    - name: Restart Tomcat
      systemd:
        name: tomcat
        state: restarted
